// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD993wsF-fqTI9avUETWWsEwrP9mHgPY88',
    appId: '1:412302383494:web:fbed773f585c2e70257407',
    messagingSenderId: '412302383494',
    projectId: 'pharmacy-employee-system-new',
    authDomain: 'pharmacy-employee-system-new.firebaseapp.com',
    storageBucket: 'pharmacy-employee-system-new.firebasestorage.app',
    measurementId: 'G-F1HLWE8FEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGCOy18BQ57hfa-WTPPGCkvSv38GDnpg8',
    appId: '1:412302383494:android:c753ccdfe804f788257407',
    messagingSenderId: '412302383494',
    projectId: 'pharmacy-employee-system-new',
    storageBucket: 'pharmacy-employee-system-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3Mk4mR_A04MuPoQXYJJ2SKdxsrS-nPc',
    appId: '1:412302383494:ios:a4708bf77b5fc920257407',
    messagingSenderId: '412302383494',
    projectId: 'pharmacy-employee-system-new',
    storageBucket: 'pharmacy-employee-system-new.firebasestorage.app',
    iosBundleId: 'com.emadfawzy.pharmacy',
  );
}
